---
title: "Untitled"
author: "MT"
date: "`r Sys.Date()`"
output: html_document
---

We'll use Python for data manipulation, statistical testing, and plotting. The analysis includes:

- Data Import
- Data Normalization
- Summary Statistics
- ANOVA and Tukey's Test
- Plotting

```{r setup, include=FALSE}


##here is what you would run in terminal to setup an environment like the rstudio environment

#conda create --name RStudio python=3.8
#conda activate RStudio
#conda install pandas matplotlib seaborn scipy statsmodels 
#conda env create -f env_config.yml

#install.packages("reticulate")


####### Is this here


# # Set Python path
#use_python(config$python_path)
# 
# # Install Python packages (optional)
# py_install(config$packages)
# 
# 
# reticulate::py_install("pandas")
# reticulate::py_install("matplotlib")
# reticulate::py_install("seaborn")
# reticulate::py_install("scipy")
# reticulate::py_install("statsmodels")

library(reticulate)
library(pandoc)



```



```{r, include = FALSE}


use_condaenv("RStudio")


```
